name: MS React Progress Bar CI

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn run test-coverage

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v1.1.2
        env:
          NODE_COVERALLS_DEBUG: 1
        with:
          github-token: ${{ secrets.REPO_TOKEN }}

      - name: Build
        run: yarn build
